# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:

import numpy as np
### [your code here]




### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print(np.__version__)
np.show_config()


2.4.6
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.31
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.31
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/Users/ec2-user/croot/numpy_and_nump

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
a = np.random.rand(2, 3, 5)



### 4. Print a.


In [5]:
### [your code here]
print (a)


[[[0.36498238 0.74944687 0.00540347 0.22438697 0.84491307]
  [0.77268285 0.29470524 0.95969949 0.70467623 0.24522284]
  [0.78552929 0.48856968 0.76518756 0.38790508 0.10781163]]

 [[0.94154483 0.7869183  0.84305124 0.3058647  0.23533352]
  [0.5261359  0.09071787 0.83456823 0.40029608 0.29402952]
  [0.48404249 0.21182808 0.7751585  0.7194034  0.17167001]]]


In [6]:
a.shape

(2, 3, 5)

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [7]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [8]:
### [your code here]
print (b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [9]:
print (b.shape)


(5, 2, 3)


In [10]:
### [your code here]
a.size == b.size

True

In [11]:
print (a.size)

30


In [12]:
print (b.size)

30


In [13]:
print (a.size == b.size)

True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
c = a + b

#No, a and b cannot be directly summed up because they contain different blocks, rows, and columns. Put differently, a and b have different dimensions/shape (2, 3, 5) & (5, 2, 3).

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [15]:
a.shape

(2, 3, 5)

In [16]:
b.shape

(5, 2, 3)



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [18]:
### [your code here]
c = np.transpose(b, (1, 2, 0))


In [19]:
print (c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [20]:
print (c.shape)

(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]
d = a + c

# It works because a and c have the same dimensions/shape (2, 3, 5), making element-wise addition possible.


In [22]:
print (d)

[[[1.36498238 1.74944687 1.00540347 1.22438697 1.84491307]
  [1.77268285 1.29470524 1.95969949 1.70467623 1.24522284]
  [1.78552929 1.48856968 1.76518756 1.38790508 1.10781163]]

 [[1.94154483 1.7869183  1.84305124 1.3058647  1.23533352]
  [1.5261359  1.09071787 1.83456823 1.40029608 1.29402952]
  [1.48404249 1.21182808 1.7751585  1.7194034  1.17167001]]]


In [23]:
print (d.shape)

(2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [24]:
### [your code here]
print (a)



[[[0.36498238 0.74944687 0.00540347 0.22438697 0.84491307]
  [0.77268285 0.29470524 0.95969949 0.70467623 0.24522284]
  [0.78552929 0.48856968 0.76518756 0.38790508 0.10781163]]

 [[0.94154483 0.7869183  0.84305124 0.3058647  0.23533352]
  [0.5261359  0.09071787 0.83456823 0.40029608 0.29402952]
  [0.48404249 0.21182808 0.7751585  0.7194034  0.17167001]]]


In [25]:
print (d)

[[[1.36498238 1.74944687 1.00540347 1.22438697 1.84491307]
  [1.77268285 1.29470524 1.95969949 1.70467623 1.24522284]
  [1.78552929 1.48856968 1.76518756 1.38790508 1.10781163]]

 [[1.94154483 1.7869183  1.84305124 1.3058647  1.23533352]
  [1.5261359  1.09071787 1.83456823 1.40029608 1.29402952]
  [1.48404249 1.21182808 1.7751585  1.7194034  1.17167001]]]


In [29]:
#the difference is the value of c in d which is absent in a 
d = a + 1

In [30]:
print(np.all(d == a + 1))

True



### 12. Multiply a and c. Assign the result to e.


In [26]:
### [your code here]
e = a * c


In [27]:
print (e)

[[[0.36498238 0.74944687 0.00540347 0.22438697 0.84491307]
  [0.77268285 0.29470524 0.95969949 0.70467623 0.24522284]
  [0.78552929 0.48856968 0.76518756 0.38790508 0.10781163]]

 [[0.94154483 0.7869183  0.84305124 0.3058647  0.23533352]
  [0.5261359  0.09071787 0.83456823 0.40029608 0.29402952]
  [0.48404249 0.21182808 0.7751585  0.7194034  0.17167001]]]


In [28]:
print (e.shape)

(2, 3, 5)




### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
np.array_equal(e, a)

#Yes. e equals a because every element of c is 1, and multiplying any number by 1 leaves the number unchanged. Therefore, e and a contain the same values.


True



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [32]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



In [34]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [35]:
print("Maximum:", d_max)
print("Minimum:", d_min)
print("Mean:", d_mean)

Maximum: 1.9596994927429865
Minimum: 1.0054034655904713
Mean: 1.5107228433948767



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [36]:
### [your code here]
f = np.empty(d.shape)


In [37]:
f = np.empty((2, 3, 5))

In [38]:
print(f.shape)

(2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [39]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100


In [40]:
print(f)

[[[ 25.  75.   0.  25.  75.]
  [ 75.  25. 100.  75.  25.]
  [ 75.  25.  75.  25.  25.]]

 [[ 75.  75.  75.  25.  25.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  25.  75.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [41]:
### [your code here]
print(d)
print(f)


[[[1.36498238 1.74944687 1.00540347 1.22438697 1.84491307]
  [1.77268285 1.29470524 1.95969949 1.70467623 1.24522284]
  [1.78552929 1.48856968 1.76518756 1.38790508 1.10781163]]

 [[1.94154483 1.7869183  1.84305124 1.3058647  1.23533352]
  [1.5261359  1.09071787 1.83456823 1.40029608 1.29402952]
  [1.48404249 1.21182808 1.7751585  1.7194034  1.17167001]]]
[[[ 25.  75.   0.  25.  75.]
  [ 75.  25. 100.  75.  25.]
  [ 75.  25.  75.  25.  25.]]

 [[ 75.  75.  75.  25.  25.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  25.  75.  75.  25.]]]


In [42]:
print(np.unique(f))

[  0.  25.  75. 100.]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [43]:
### [your code here]
f = np.empty(d.shape, dtype=str)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = "A"
            elif d[i, j, k] < d_mean:
                f[i, j, k] = "B"
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "C"
            elif d[i, j, k] < d_max:
                f[i, j, k] = "D"
            else:
                f[i, j, k] = "E"

print(f)

[[['B' 'D' 'A' 'B' 'D']
  ['D' 'B' 'E' 'D' 'B']
  ['D' 'B' 'D' 'B' 'B']]

 [['D' 'D' 'D' 'B' 'B']
  ['D' 'B' 'D' 'B' 'B']
  ['B' 'B' 'D' 'D' 'B']]]


In [44]:
np.empty(d.shape, dtype=str)

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')